id = "jwt"
name = "JWT"
version = "0.1.0"
schema_version = 1
authors = ["Marcus Cvjeticanin <mjovanc@icloud.com>"]
description = "Validate and decode JWT tokens for Zed"
repository = "https://github.com/mjovanc/zed-jwt"

[slash_commands.jwt]
description = "JWT tools: decode or verify tokens"
requires_argument = true
