id = "jwt"
name = "JWT"
version = "0.1.3"
schema_version = 1
authors = ["Marcus Cvjeticanin <mjovanc@icloud.com>"]
description = "Validate and decode JWT tokens for Zed"
repository = "https://github.com/mjovanc/zed-jwt"

[slash_commands.jwt]
description = "JWT tools: Use 'decode <token>' or 'verify <token> <key>'"
requires_argument = true
